version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cinema
      - MYSQL_USER=cinemauser
      - MYSQL_PASSWORD=cinemauser
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
