version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cinema
      - MYSQL_USER=cinemauser
      - MYSQL_PASSWORD=cinemauser
    ports:
      - "3319:3306"
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d

